config/routes.rb
Expenses::Application.routes.draw do
  resources :expenses, except: [:destroy]
  resources :months, except: [:destroy]
  resources :stats, only: [:index]

  root :to => 'stats#index'
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  has_many :month_expenses, dependent: :destroy, inverse_of: :expense
  has_many :months, through: :month_expenses

  validates_presence_of :name, :weight
  validates_uniqueness_of :name

  attr_accessible :name, :weight, :is_active

  scope :ordered, ->() { order('weight DESC') }
  scope :active, ->() { where(is_active: true) }
end

app/models/month.rb
class Month < ActiveRecord::Base
  after_create :generate_month_expenses, if: Proc.new { |m| m.month_expenses.blank? }

  has_many :month_expenses, dependent: :destroy, inverse_of: :month
  has_many :expenses, through: :month_expenses

  validates_presence_of :name

  attr_accessible :name, :result, :month_expenses_attributes

  accepts_nested_attributes_for :month_expenses

  scope :ordered, -> { order('id DESC') }

private

  def generate_month_expenses
    Expense.active.ordered.each do |expense|
      MonthExpense.create(month_id: self.id, expense_id: expense.id)
    end
  end
end

app/models/month_expense.rb
class MonthExpense < ActiveRecord::Base
  belongs_to :month
  belongs_to :expense

  validates_presence_of :month_id, :expense_id
  validates_uniqueness_of :month_id, scope: :expense_id

  attr_accessible :month_id, :expense_id, :sum_real, :desc

  def calculate_sum_real
    if (sum_real.to_s == '0' || sum_real.blank?) && desc.present?
      if desc.match(/[0-9\+\s]+/)[0] == desc
        sum = eval(desc) rescue 0
        if sum > 0
          self.sum_real = sum
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @expenses = Expense.ordered
  end

  def show
    @expense = Expense.ordered.includes(:months).find(params[:id])
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(params[:expense])

    if @expense.save
      redirect_to expenses_path
    else
      render :edit
    end
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def update
    @expense = Expense.find(params[:id])
    if @expense.update_attributes(params[:expense])
      redirect_to expense_path(@expense)
    else
      render :edit
    end
  end
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  def index
    @months = Month.ordered
  end

  def show
    @month = Month.ordered.includes(:expenses).find(params[:id])
  end

  def new
    @month = Month.new
  end

  def create
    @month = Month.new(params[:month])

    if @month.save
      redirect_to months_path
    else
      render :edit
    end
  end

  def edit
    @month = Month.includes(:expenses).find(params[:id])
  end

  def update
    @month = Month.find(params[:id])
    if @month.update_attributes(params[:month])
      @month.month_expenses.each do |me|
        me.calculate_sum_real
        me.save
      end

      redirect_to month_path(@month)
    else
      render :edit
    end
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/_form.html.erb
<%= simple_form_for @expense, html: { class: 'form-horizontal' } do |f| %>
    <%= f.input :name %>
    <%= f.input :weight, label: "Weight" %>
    <%= f.input :is_active, label: "Active?" %>
    <br/>
    <%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/expenses/edit.html.erb
<h1>Edit Expense <small>update content</small></h1>

<%= render 'form' %>

app/views/expenses/index.html.erb
<h1>
  <%= link_to 'New Expense', new_expense_path, class: 'btn btn-primary' %>
  Expenses
  <small>list of all tracked expense</small>
</h1>

<table class="table">
  <thead>
  <tr>
    <th>Weight</th>
    <th>Name</th>
    <th>Active?</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @expenses.each do |expense| %>
      <tr>
        <td>
          <%= expense.weight %>
        </td>
        <td>
          <%= link_to expense.name, expense_path(expense) %>
        </td>
        <td>
          <%= expense.is_active? ? 'yes' : 'no' %>
        </td>
        <td>
          <%= link_to 'Edit', edit_expense_path(expense), class: 'btn btn-primary btn-mini' %>
        </td>
      </tr>
  <% end %>
  </tbody>
  <thead>
  <tr>
    <th>Weight</th>
    <th>Name</th>
    <th>Active?</th>
    <th>Actions</th>
  </tr>
  </thead>
</table>

app/views/expenses/new.html.erb
<h1>New Expense <small>add one</small></h1>

<%= render 'form' %>

app/views/expenses/show.html.erb
<h1>
  <%= link_to 'Edit', edit_expense_path(@expense), class: 'btn btn-primary' %>
  <%= @expense.name %>
</h1>

<table class="table">
  <thead>
  <tr>
    <th>Month</th>
    <th>Sum</th>
    <th>Description</th>
  </tr>
  </thead>
  <tbody>
  <% @expense.month_expenses.each do |month_expense| %>
      <tr>
        <td>
          <%= link_to month_expense.month.name, month_path(month_expense.month) %>
        </td>
        <td>
          <%= month_expense.sum_real %>
        </td>
        <td>
          <%= month_expense.desc %>
        </td>
      </tr>
  <% end %>
  </tbody>
  <thead>
  <tr>
    <th>Month</th>
    <th>Sum</th>
    <th>Description</th>
  </tr>
  </thead>
</table>

app/views/layouts/_navigation.html.erb
<%= link_to "Expenses", root_path, class: 'brand' %>

<div class="nav-collapse collapse">
  <ul class="nav pull-left">
    <li class="<%= current_page?(months_path) ? 'active' : '' %>">
      <%= link_to 'Months', months_path %>
    </li>
    <li class="<%= current_page?(expenses_path) ? 'active' : '' %>">
      <%= link_to('Expenses', expenses_path) %>
    </li>
    <li class="<%= current_page?(stats_path) ? 'active' : '' %>">
      <%= link_to('Stats', stats_path) %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Expenses</title>
  <meta name="description" content="expenses tracker">
  <meta name="author" content="">
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
<header class="navbar navbar-fixed">
  <nav class="navbar-inner">
    <div class="container">
      <%= render 'layouts/navigation' %>
    </div>
  </nav>
</header>
<div class="container">
  <div class="content">
    <div class="row">
      <div class="span12">
        <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
              <a class="close" data-dismiss="alert">×</a>
              <%= msg %>
            </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
    <br/>
    <footer class="footer">
      <p>
        <small>
          Copyright © 2012 rilian
          <br/>
          This site is based on <a href="https://github.com/rilian/expenses" rel="nofollow">rilian/expenses</a> engine.
        </small>
      </p>
    </footer>
  </div>
</div>
</body>
</html>

app/views/months/_form.html.erb
<%= simple_form_for @month, html: { class: 'form-horizontal' } do |f| %>
  <%= f.input :name, input_html: { class: "input-xxlarge" } %>
  <%= f.input :result, as: :text, input_html: { rows: 2, cols: 40, class: "input-xxlarge" } %>
  <br/>
  <%= f.button :submit, class: 'btn-primary' %>

  <% if @month.month_expenses.size > 0 %>
    <table class="table">
      <thead>
      <tr>
        <th>Expense</th>
        <th>Sum</th>
        <th>Description</th>
      </tr>
      </thead>
      <tbody>
        <%= f.simple_fields_for :month_expenses, @month.month_expenses.joins(:expense).order('expenses.weight DESC') do |month_expense| %>
        <tr>
          <td><%= month_expense.object.expense.name %></td>
          <td><%= month_expense.input :sum_real, as: :integer, label: false %></td>
          <td><%= month_expense.input :desc, input_html: { class: "input-xxlarge" }, label: false %></td>
        </tr>
        <% end %>
      </tbody>
    <table>
    <%= f.button :submit, class: 'btn-primary' %>
  <% else %>
    <br/>
    <br/>
    <p>Note: Expenses will be generated once month is successfully created</p>
  <% end %>
<% end %>

app/views/months/edit.html.erb
<h1>Edit Month <small>update content</small></h1>

<%= render 'form' %>

app/views/months/index.html.erb
<h1>
  <%= link_to 'New Month', new_month_path, class: 'btn btn-primary' %>
  Months
  <small>list of all tracked month</small>
</h1>

<table class="table">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Real expenses sum</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @months.each do |month| %>
      <tr>
        <td>
          <%= month.id %>
        </td>
        <td>
          <%= link_to month.name, month_path(month) %>
        </td>
        <td>
          <%= month.month_expenses.sum('month_expenses.sum_real') %>
        </td>
        <td>
          <%= link_to 'Edit', edit_month_path(month), class: 'btn btn-primary btn-mini' %>
        </td>
      </tr>
  <% end %>
  </tbody>
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Real expenses sum</th>
    <th>Actions</th>
  </tr>
  </thead>
</table>

app/views/months/new.html.erb
<h1>New Month <small>add one</small></h1>

<%= render 'form' %>

app/views/months/show.html.erb
<h1>
  <%= link_to 'Edit', edit_month_path(@month), class: 'btn btn-primary' %>
  <%= @month.name %>
</h1>

<table class="table">
  <thead>
  <tr>
    <th>Expense</th>
    <th>Sum</th>
    <th>Description</th>
  </tr>
  </thead>
  <tbody>
  <% @month.month_expenses.joins(:expense).order('expenses.weight DESC').each do |month_expense| %>
      <tr>
        <td>
          <%= link_to month_expense.expense.name, expense_path(month_expense.expense) %>
        </td>
        <td>
          <%= month_expense.sum_real %>
        </td>
        <td>
          <%= month_expense.desc %>
        </td>
      </tr>
  <% end %>
  </tbody>
  <thead>
  <tr>
    <th>Expense</th>
    <th>Sum</th>
    <th>Description</th>
  </tr>
  </thead>
</table>

app/views/stats/index.html.erb
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load('visualization', '1.0', {packages: ['corechart']});
  </script>

  <script type="text/javascript">
  <% Expense.active.ordered.each do |expense| %>
      function drawVisualization<%= expense.id %>() {
        // Create and populate the data table.
        var data = google.visualization.arrayToDataTable([
          ['x', '<%= Time.now.year.to_s %>', '<%= (Time.now - 1.years).year.to_s %>', '<%= (Time.now - 2.years).year.to_s %>', '<%= (Time.now - 3.years).year.to_s %>', '<%= (Time.now - 4.years).year.to_s %>'],
          <% Month.limit(12).order('id DESC').reverse.each do |month| %>
            ['<%= month.name.gsub(/\d+/, '') %>',
              <%= MonthExpense.where(month_id: month.id, expense_id: expense.id).first.try(:sum_real) || 0 %>,
              <%= MonthExpense.where(month_id: month.id-12, expense_id: expense.id).first.try(:sum_real) || 0 %>,
              <%= MonthExpense.where(month_id: month.id-24, expense_id: expense.id).first.try(:sum_real) || 0 %>,
              <%= MonthExpense.where(month_id: month.id-36, expense_id: expense.id).first.try(:sum_real) || 0 %>,
              <%= MonthExpense.where(month_id: month.id-48, expense_id: expense.id).first.try(:sum_real) || 0 %>
            ],
          <% end %>
        ]);

        // Create and draw the visualization.
        new google.visualization.LineChart(document.getElementById('visualization_<%= expense.id %>')).
          draw(data, {curveType: "none",
            width: 940, height: 500,
            vAxis: {maxValue: 10},
            chartArea:{left:50,top:30,width:880,height:400},
            legend: {position: 'top', textStyle: {color: 'blue', fontSize: 16}}
          }
        );
      }
      google.setOnLoadCallback(drawVisualization<%= expense.id %>);
  <% end %>
  </script>
</head>
<body style="font-family: Arial;border: 0 none;">
  <% Expense.active.ordered.all.each do |expense| %>
    <h2><%= link_to expense.name, expense_path(expense) %></h2>
    <div id="visualization_<%= expense.id %>" style="width: 940px; height: 550px;"></div>
  <% end %>
</body>
</html>